# Generated by Django 6.1.1 on 2026-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercado',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='email_comercial',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
