# Generated by Django 6.1.1 on 2026-10-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_supermercado_bairro_supermercado_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='supermercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.supermercado'),
        ),
    ]
