# Generated by Django 6.1.1 on 2026-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_supermercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercado',
            name='senha',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
