# Generated by Django 6.1.1 on 2026-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_supermercado_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
