# Generated by Django 6.1.1 on 2026-10-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual'), ('valor', 'Valor fixo')], default='percentual', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('limite_uso', models.PositiveIntegerField(blank=True, null=True)),
                ('usos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
