# Generated by Django 6.1.1 on 2026-10-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando pagamento'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(default='mercado_pago', max_length=50)),
                ('forma_pagamento', models.CharField(default='pix', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pendente', max_length=50)),
                ('status_detail', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('ticket_url', models.URLField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='produtos.pedido')),
            ],
        ),
    ]
